---
- name: Playbook to check server version
  #hosts: localhost
  hosts: webserver

  tasks:
   - name: Check the version of server tomcat
     shell:
             /home/ec2-user/apache-tomcat-9.0.39/bin/version.sh ; #>> /home/ec2-user/apache-tomcat-9.0.39/bin/somelog
     
     register: toms_version

   - debug:
       var: toms_version.stdout_lines
     tags: check_version
    
  - name: Stop the server tomcat from UI
     shell:
             /home/ec2-user/apache-tomcat-9.0.39/bin/shutdown.sh ;#>> /home/ec2-user/apache-tomcat-9.0.39/bin/somelog
              pgrep -x java >/dev/null && echo "Process found" || echo "Process not found";
 
     register: toms_process
   - debug:
       var: toms_process.stdout_lines
      tags: stop_server
