---
- name: Playbook to stop server
  #hosts: localhost
  hosts: webserver

  tasks:
   - name: Stop the server tomcat from UI
     shell:
             /home/ec2-user/apache-tomcat-9.0.39/bin/shutdown.sh ;#>> /home/ec2-user/apache-tomcat-9.0.39/bin/somelog
              pgrep -x java >/dev/null && echo "Process found" || echo "Process not found";
 
     register: toms_process
   - debug:
       var: toms_process.stdout_lines

